### ISSUE TITLE
Import large dictionary freezes progressbar

### ISSUE THREAD

**Issue by mighele** [old-account-392754/StenoLite#2]
Trying to import my dictionary (200,000 line json file), the progressbar goes about 3/4s of the way across and then stops. Eventually it crashed, (I think I went to type in another window while it was importing the dictionary).

**Comment by old-account-392754** [comment]
I would love to address this problem, but I need to see that dictionary file itself, as its size by itself is not the explanation (the SKH files were created by importing a 3000,000+ json file).  So if you could upload it to google docs, or find some other way to make it available, that would be awesome.

**Comment by old-account-392754** [comment]
Further research on my part revealed what I think was a threading problem that could have caused your problem.  And I think I have it fixed for the next release.  But I suppose that we will see ....
