### ISSUE TITLE
After dictionary import crash, app won't start

### ISSUE THREAD

**Issue by mighele** [old-account-392754/StenoLite#3]
App crashed after importing my dictionary. After this crash, starting the app shows two messageboxes "Failed to open dictionary", "Failed to open secondary index" and then crashes.

**Comment by old-account-392754** [comment]
I have added some more robust error detection and recovery in 0.8.3.  I can't promise that every dictionary will be recoverable after a crash, but at least bad files shouldn't cause StenoLite to crash or hang on subsequent launches.
